apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: inkless-kafka-exporter-podmonitor
spec:
  selector:
    matchLabels:
      strimzi.io/name: inkless-kafka-exporter
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus